add_subdirectory(BLAS1)
add_subdirectory(Eigen)
add_subdirectory(MatrixDecomp)
add_subdirectory(VectorExpr)

target_sources(Benchmark PRIVATE GEMM.cpp)
target_sources(Benchmark PRIVATE IdentityMV.cpp)
target_sources(Benchmark PRIVATE SyMV.cpp)
target_sources(Benchmark PRIVATE Transpose.cpp)
if(${PHYSICA_MKL})
    target_sources(Benchmark PRIVATE GEMM_MKL.cpp)
    target_sources(Benchmark PRIVATE Transpose_MKL.cpp)
endif()
