# Core
## Math
### Calculus
physica_add_test(FokkerPlanck Core/Math/Calculus/PDE/FEM/FokkerPlanck.cpp)
### Optimization
physica_add_test(Adam Core/Math/Optimization/AdamTest.cpp)
## Physics
physica_add_test(DimEstimator Core/Physics/DimEstimator.cpp)
physica_add_test(KSSolver Core/Physics/KSSolver.cpp)