physica_add_test(EigenSolver Eigen/EigenSolver.cpp)
physica_add_test(JacobiDavidson Eigen/JacobiDavidson.cpp)
physica_add_test(SymmEigenSolver Eigen/SymmEigenSolver.cpp)

add_subdirectory(Matrix)

physica_add_test(DiffVector Vector/DiffVector.cpp)
physica_add_test(Givens Vector/Givens.cpp)
physica_add_test(HouseHolder Vector/HouseHolder.cpp)
physica_add_test(Vector Vector/Vector.cpp)
physica_add_test(LinearEquations LinearEquations/LinearEquations.cpp)
physica_add_test(LUSolver LinearEquations/LUSolver.cpp)
if(${PHYSICA_CUDA})
    physica_add_test(Vector_cuda Vector/Vector.cu)
endif()
