message(STATUS "Performing CheckEndian")
try_run(RUN_RESULT_VAR COMPILE_RESULT_VAR ${CMAKE_BINARY_DIR} ${CMAKE_HOME_DIRECTORY}/Config/Check/CheckEndian.cpp)
if(NOT ${COMPILE_RESULT_VAR})
    message(FATAL_ERROR Failed to compile CheckEndian.cpp)
endif()

if(${RUN_RESULT_VAR} MATCHES FAILED_TO_RUN)
    message(FATAL_ERROR Failed to run CheckEndian)
endif()

if(${RUN_RESULT_VAR} MATCHES 1)
    message(STATUS "Performing CheckEndian --BigEndian")
    set(PhysicaEndian PhysicaBigEndian)
else()
    message(STATUS "Performing CheckEndian --LittleEndian")
    set(PhysicaEndian PhysicaLittleEndian)
endif()