target_sources(Benchmark PRIVATE Asum.cpp)
target_sources(Benchmark PRIVATE Axpy.cpp)
target_sources(Benchmark PRIVATE Copy.cpp)
target_sources(Benchmark PRIVATE Dot.cpp)
target_sources(Benchmark PRIVATE Nrm2.cpp)
target_sources(Benchmark PRIVATE Scal.cpp)

add_subdirectory(Dispatch)
if(${PHYSICA_MKL})
    add_subdirectory(MKL)
endif()

if(${PHYSICA_CUDA})
    target_sources(Benchmark PRIVATE Axpy.cu)
endif()
