# AI
physica_add_example(DecisionTree AI/DecisionTree.cpp)
physica_add_example(Mnist AI/Mnist.cpp)
physica_add_example(Mnist_cuda AI/Mnist.cu)
# Math
physica_add_example(DuffingOscillator Math/DuffingOscillator.cpp)
physica_add_example(FokkerPlanck Math/FokkerPlanck.cpp)
physica_add_example(ProbabilityDistributionFunction2D Math/ProbabilityDistributionFunction2D.cpp)

add_subdirectory(Physics)
