find_path(GPerfTools_INCLUDE_DIR gperftools/tcmalloc.h)
find_library(GPerfTools_LIBRARY profiler)

set(GPerfTools_INCLUDE_DIRS ${GPerfTools_INCLUDE_DIR})
set(GPerfTools_LIBRARIES ${GPerfTools_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GPerfTools DEFAULT_MSG GPerfTools_INCLUDE_DIR GPerfTools_LIBRARY)

mark_as_advanced(GPerfTools_INCLUDE_DIR GPerfTools_LIBRARY)
