file(GLOB_RECURSE HEADERS ${CMAKE_HOME_DIRECTORY}/include/*.h ${CMAKE_HOME_DIRECTORY}/include/*.cuh)
set(PHYSICA_EXAMPLE_LIBS PhysicaCore pthread ${GPerfTools_LIBRARY})

function(physica_add_example NAME SOURCES)
    add_executable(Example-${NAME} ${SOURCES} ${ARGN} ${HEADERS})
    target_link_libraries(Example-${NAME} ${PHYSICA_EXAMPLE_LIBS})
    if(${PHYSICA_GUI})
        set_target_properties(Example-${NAME} PROPERTIES AUTOMOC ON)
        target_link_libraries(Example-${NAME} PhysicaGui)
    endif()
    install(TARGETS Example-${NAME} DESTINATION examples)
endfunction()
