get_filename_component(Physica_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(Physica_INCLUDE_DIRS "${Physica_ROOT_DIR}/include")

list(APPEND PhysicaModules AI Core Gui Logger Utils)
foreach (module IN LISTS PhysicaModules)
    set(Physica${module}_LIBRARIES "${Physica_ROOT_DIR}/lib/libPhysica${module}.so")
    if (EXISTS ${Physica${module}_LIBRARIES})
        set(Physica${module}_FOUND TRUE)
        list(APPEND Physica_LIBRARIES ${Physica${module}_LIBRARIES})
    else()
        set(Physica${module}_FOUND FALSE)
        unset(Physica${module}_LIBRARIES)
    endif()
endforeach()

if (EXISTS "${Physica_INCLUDE_DIRS}/Physica/Config.h")
    set(Physica_FOUND TRUE)
else()
    set(Physica_FOUND FALSE)
endif()
