name: Build-Test Minimal

on:
  push:
    branches: [ "Physica", "dev" ]
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    branches: [ "Physica", "dev" ]
  workflow_dispatch:

jobs:
  debug:
    uses: ./.github/workflows/preset-minimal.yml
    with:
      build_config: Debug

  release:
    needs: debug
    uses: ./.github/workflows/preset-minimal.yml
    with:
      build_config: Release
