name: clang-format

on:
  push:
    branches: [ "Physica" ]
  pull_request:
    branches: [ "Physica" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 2

    - name: Install
      run: |
        sudo apt-get install -y clang-format-20

    - name: Run clang-format
      run: |
        git clang-format-20 HEAD^ --diff --binary=`which clang-format-20`
