name: Build-Test Minimal Preset
on:
  workflow_call:
    inputs:
      build_config:
        required: true
        type: string
        description: 'Debug or Release'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Install ccache
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        key: Minimal-${{ inputs.build_config }}

    - name: Install clang
      uses: egor-tensin/setup-clang@v2.3
      with:
        version: 23
        platform: # optional, default is x64
        cc: # optional, default is 1

    - name: Install dependency
      run: |
        sudo apt-get install libfftw3-dev

    - name: Configure
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_config }} \
          -DCMAKE_C_COMPILER=clang-23 \
          -DCMAKE_CXX_COMPILER=clang++-23 \
          -DCMAKE_LINKER_TYPE=LLD \
          -DCMAKE_CXX_FLAGS=-Werror \
          -DPHYSICA_CCACHE=ON

    - name: Build
      run: |
        cd build
        cmake --build .  --parallel

    - name: Test
      run: |
        cd build/test
        ctest --parallel --output-on-failure .
